// src/entities/titlePage/model/presets.ts
import { TitlePageData } from "./types";

export const TITLE_PAGE_PRESETS: TitlePageData[] = [
  {
    id: "preset-standard-6-8",
    presetName: "Стандартный КТП (6А, 6Б, 7, 8 классы)",
    academicYear: "2024-2025",
    approvedBy: {
      titleKz: "Бекітемін",
      titleRu: "Утверждено",
      positionKz: "Директор",
      positionRu: "Директор:",
      name: "Мельников П.В.",
    },
    agreedBy: {
      titleKz: "Келісемін",
      titleRu: "Согласовано",
      positionKz: "оқу ісі меңгерушісінің м.а.",
      positionRu: "И.о. Завуч:",
      name: "Ильясова А.Б.",
    },
    reviewedBy: {
      titleKz: "әдістемелік бірлестікте қарастырылды",
      titleRu: "рассмотрено на заседании МО",
      bodyKz: "№ ___ хаттама",
      bodyRu: "Протокол № ________",
      protocolNo: "",
      protocolYear: "2024",
      headName: "Красноперова О.В.",
    },
    titleKz: "Күнтізбелік-тақырыптық жоспарлау 2024-2025 оқу жылына",
    titleRu: "Календарно-тематическое планирование на 2024-2025 учебный год",
    isSpecialEd: false,
    subjectKz: "математика, алгебра, геометрия",
    subjectRu: "математика, алгебра, геометрия",
    grade: "6А, 6Б, 7, 8",
    teacherName: "Бабич И.Д.",
  },
  {
    id: "preset-oop-6b-turgunbaeva",
    presetName: "ООП (ЛУО) 6Б класс — Тургунбаева Айсана",
    academicYear: "2024-2025",
    approvedBy: {
      titleKz: "Бекітемін",
      titleRu: "Утверждено",
      positionKz: "Директор",
      positionRu: "Директор:",
      name: "Мельников П.В.",
    },
    agreedBy: {
      titleKz: "Келісемін",
      titleRu: "Согласовано",
      positionKz: "оқу ісі меңгерушісінің м.а.",
      positionRu: "И.о. Завуч:",
      name: "Ильясова А.Б.",
    },
    reviewedBy: {
      titleKz: "әдістемелік бірлестікте қарастырылды",
      titleRu: "рассмотрено на заседании МО",
      bodyKz: "№ ___ хаттама",
      bodyRu: "Протокол № ________",
      protocolNo: "",
      protocolYear: "2024",
      headName: "Красноперова О.В.",
    },
    titleKz: "Ерекше білім беру қажеттіліктері бар білім алушыларға арналған күнтізбелік-тақырыптық жоспарлау (интеллекттің жеңіл бұзылуы) 2024-2025 оқу жылына 6 «Б» сынып(Тургунбаева Айсана)",
    titleRu: "Календарно-тематическое планирование для обучающихся с особыми образовательными потребностями( легкое нарушение интеллекта) на 2024-2025 учебный год 6 «Б» класс (Тургунбаева Айсана)",
    isSpecialEd: true,
    specialEdCategoryKz: "интеллекттің жеңіл бұзылуы",
    specialEdCategoryRu: "легкое нарушение интеллекта",
    studentName: "Тургунбаева Айсана",
    subjectKz: "математика",
    subjectRu: "математика",
    grade: "6Б",
    teacherName: "Бабич И.Д.",
  },
  {
    id: "preset-oop-8-potanin",
    presetName: "ООП (ЛУО) 8 класс — Потанин Борис",
    academicYear: "2024-2025",
    approvedBy: {
      titleKz: "Бекітемін",
      titleRu: "Утверждено",
      positionKz: "Директор",
      positionRu: "Директор:",
      name: "Мельников П.В.",
    },
    agreedBy: {
      titleKz: "Келісемін",
      titleRu: "Согласовано",
      positionKz: "оқу ісі меңгерушісінің м.а.",
      positionRu: "И.о. Завуч:",
      name: "Ильясова А.Б.",
    },
    reviewedBy: {
      titleKz: "әдістемелік бірлестікте қарастырылды",
      titleRu: "рассмотрено на заседании МО",
      bodyKz: "№ ___ хаттама",
      bodyRu: "Протокол № ________",
      protocolNo: "",
      protocolYear: "2024",
      headName: "Красноперова О.В.",
    },
    titleKz: "Ерекше білім беру қажеттіліктері бар білім алушыларға арналған күнтізбелік-тақырыптық жоспарлау (интеллекттің жеңіл бұзылуы) 2024-2025 оқу жылына 8 сынып(Потанин Борис)",
    titleRu: "Календарно-тематическое планирование для обучающихся с особыми образовательными потребностями( легкое нарушение интеллекта) на 2024-2025 учебный год 8 класс (Потанин Борис)",
    isSpecialEd: true,
    specialEdCategoryKz: "интеллекттің жеңіл бұзылуы",
    specialEdCategoryRu: "легкое нарушение интеллекта",
    studentName: "Потанин Борис",
    subjectKz: "математика",
    subjectRu: "математика",
    grade: "8",
    teacherName: "Бабич И.Д.",
  },
];
