export const SUBJECT_NAMES: Record<string, string> = {
  alphabet: "Әліппе",
  bukvar: "Букварь",
  gramota: "Обучение грамоте",
  elipbe: "Елипбә",
  alifbe: "Алифбе",
  alifbo: "Алифбо",
  ana_tili: "Ана тілі",
  mathematics: "Математика",
  digital_literacy: "Цифровая грамотность",
  natural_science: "Естествознание",
  world_knowledge: "Познание мира",
  visual_art: "Изобразительное искусство",
  labor_training: "Трудовое обучение",
  art_work: "Художественный труд",
  music: "Музыка",
  physical_education: "Физическая культура",
  literary_reading: "Литературное чтение",
  kazakh_language: "Казахский язык",
  kazakh_tili: "Қазақ тілі",
  russian_language: "Русский язык",
  uigur_language: "Уйгурский язык",
  uzbek_language: "Узбекский язык",
  tadzhik_language: "Таджикский язык",
  english: "Английский язык",
  german: "Немецкий язык",
  french: "Французский язык",
  kazakh_literature: "Казахская литература",
  kazakh_adebieti: "Қазақ әдебиеті",
  russian_literature: "Русская литература",
  uigur_literature: "Уйгурская литература",
  uzbek_literature: "Узбекская литература",
  tadzhik_literature: "Таджикская литература",
  kazakh_language_literature: "Казахский язык и литература",
  russian_language_literature: "Русский язык и литература",
  algebra: "Алгебра",
  geometry: "Геометрия",
  algebra_analysis: "Алгебра и начала анализа",
  informatics: "Информатика",
  physics: "Физика",
  chemistry: "Химия",
  biology: "Биология",
  geography: "География",
  kazakhstan_history: "История Казахстана",
  world_history: "Всемирная история",
  law_fundamentals: "Основы права",
  abaitanu: "Абайтану",
  regional_studies: "Краеведение",
  graphics_design: "Графика и проектирование",
  military_training: "НВТП",
  entrepreneurship: "Основы предпринимательства и бизнеса",
};

export const SUBJECT_NAMES_KZ: Record<string, string> = {
  alphabet: "Әліппе",
  bukvar: "Букварь",
  gramota: "Сауат ашу",
  elipbe: "Еліппе",
  alifbe: "Әлифбе",
  alifbo: "Алифбо",
  ana_tili: "Ана тілі",
  mathematics: "Математика",
  digital_literacy: "Цифрлық сауаттылық",
  natural_science: "Жаратылыстану",
  world_knowledge: "Дүниетану",
  visual_art: "Бейнелеу өнері",
  labor_training: "Еңбекке баулу",
  art_work: "Көркем еңбек",
  music: "Музыка",
  physical_education: "Дене шынықтыру",
  literary_reading: "Әдебиеттік оқу",
  kazakh_language: "Қазақ тілі",
  kazakh_tili: "Қазақ тілі",
  russian_language: "Орыс тілі",
  uigur_language: "Ұйғыр тілі",
  uzbek_language: "Өзбек тілі",
  tadzhik_language: "Тәжік тілі",
  english: "Ағылшын тілі",
  german: "Неміс тілі",
  french: "Француз тілі",
  kazakh_literature: "Қазақ әдебиеті",
  kazakh_adebieti: "Қазақ әдебиеті",
  russian_literature: "Орыс әдебиеті",
  uigur_literature: "Ұйғыр әдебиеті",
  uzbek_literature: "Өзбек әдебиеті",
  tadzhik_literature: "Тәжік әдебиеті",
  kazakh_language_literature: "Қазақ тілі және әдебиеті",
  russian_language_literature: "Орыс тілі және әдебиеті",
  algebra: "Алгебра",
  geometry: "Геометрия",
  algebra_analysis: "Алгебра және анализ бастамалары",
  informatics: "Информатика",
  physics: "Физика",
  chemistry: "Химия",
  biology: "Биология",
  geography: "География",
  kazakhstan_history: "Қазақстан тарихы",
  world_history: "Дүниежүзі тарихы",
  law_fundamentals: "Құқық негіздері",
  abaitanu: "Абайтану",
  regional_studies: "Өлкетану",
  graphics_design: "Графика және жобалау",
  military_training: "Алғашқы әскери және технологиялық дайындық",
  entrepreneurship: "Кәсіпкерлік және бизнес негіздері",
};

export function subjectName(subjectId: string, language?: string): string {
  if (language === "kz") return SUBJECT_NAMES_KZ[subjectId] ?? SUBJECT_NAMES[subjectId] ?? subjectId;
  return SUBJECT_NAMES[subjectId] ?? SUBJECT_NAMES_KZ[subjectId] ?? subjectId;
}
